filter:
    excluded_paths:
        - 'vendor/*'
before_commands:
    # Use --prefer-source to download dependencies via git and avoid GitHub API
    # rate limits resulting in 502 HTTP responses, build errors and
    # Composer\Downloader\TransportException.
    # https://github.com/symfony/symfony/issues/4687
    - 'composer install --dev --no-interaction --prefer-source'
tools:
    php_mess_detector:
        config:
            code_size_rules: { cyclomatic_complexity: false, npath_complexity: false }
    php_code_sniffer:
        config:
            standard: PSR2
    php_code_coverage:
        test_command: vendor/bin/phpunit
    php_cpd: true
    php_pdepend: true
